### ISSUE TITLE
安装supervisor过程中提示错误

### ISSUE THREAD

**Issue by senri0079** [kuoruan/shell-scripts#29]
这几天网络升级了。有人提出解决方案是使用kcptun。找到您的脚本安装中出现以下错误。
+ pip install supervisor
Traceback (most recent call last):
  File "/usr/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python2.6/site-packages/pip/_internal/__init__.py", line 19, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 92
    _blocking_errnos = {errno.EAGAIN, errno.EWOULDBLOCK}
用命令手动安装也出现相同错误。我的环境是CentOS 6 x64。望得到您的解答。
顺颂时祺

**Comment by kuoruan** [comment]
你重新下载一下脚本，再次安装

**Comment by kuoruan** [comment]
如果还是不行的话，手动执行一下：

```
wget -qO- --no-check-certificate https://bootstrap.pypa.io/2.6/get-pip.py | python
```

**Comment by senri0079** [comment]
感谢！安装完成
