### ISSUE TITLE
pip安装失败

### ISSUE THREAD

**Issue by zishuaiz** [kuoruan/shell-scripts#54]
服务器是ubuntu 20.04, python3.8， python3.7, python2都试过了，报下面的错误：

```
2021-01-30 17:12:50 (63.8 MB/s) - ‘kcptun-v20210103.tar.gz’ saved [6367092/6367092]

+ sha1sum -c
+ echo '31ced1ecd7adefdc62d1f311e88d9d307c229dc8  kcptun-v20210103.tar.gz'
kcptun-v20210103.tar.gz: OK
+ tar -zxf kcptun-v20210103.tar.gz -C /usr/local/kcptun
+ sleep 3
+ python
+ wget -qO- --no-check-certificate https://bootstrap.pypa.io/get-pip.py
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpEXomXf/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

环境已经有pip了，为啥还要get-pip.py | python ?

**Comment by kuoruan** [comment]
```python -V```

看看是什么版本？

**Comment by zishuaiz** [comment]
> `python -V`
> 
> 看看是什么版本？

ubuntu 20.04系统默认是py3.8, 通过conda装了py2, py37，都试了下，报同样的错误
怀疑是脚本哪里没有载入系统环境，因为在命令行运行 python -v, pip --version， which python which pip都是正常的，但是脚本没有检测到这些变量

**Comment by kuoruan** [comment]
https://github.com/kuoruan/shell-scripts/blob/master/kcptun/kcptun.sh#L807

脚本会先执行 `command -v python` 判断是否已经安装python，然后 `python -V` 看 python 版本，看看你 `python -V` 输出的版本号是什么

**Comment by zishuaiz** [comment]
换了个centos 7.x，还是报一样的问题
cent7下python -V输出：Python 2.7.5

**Comment by kuoruan** [comment]
`command -v python` python 在哪个路径？

**Comment by zishuaiz** [comment]
```bash
++ echo 2.7.5
++ cut -d. -f1
+ local major_version=2
++ echo 2.7.5
++ cut -d. -f2
+ local minor_version=7
+ '[' -z 2 ']'
+ '[' -z 7 ']'
+ is_number 2
+ expr 2 + 1
+ local is_python_26=false
+ '[' 2 -lt 2 ']'
+ '[' 2 = 2 ']'
+ '[' 7 -lt 6 ']'
+ '[' 2 = 2 ']'
+ '[' 7 = 6 ']'
+ command_exists pip
+ command -v pip
+ command_exists pip
+ command -v pip
+ pip --version
+ cat
检测到当前环境的 pip 命令已损坏，
请检查你的 python 环境。
+ exit 1
[root@hwsrv-814705 ~]# command -v python
/usr/bin/python
[root@hwsrv-814705 ~]# 
[root@hwsrv-814705 ~]# 
[root@hwsrv-814705 ~]# 
[root@hwsrv-814705 ~]# 
[root@hwsrv-814705 ~]# python
Python 2.7.5 (default, Nov 16 2020, 22:23:17) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
```

**Comment by kuoruan** [comment]
`pip --version`
